---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opengist-data
  labels:
    app.kubernetes.io/name: opengist
    app.kubernetes.io/component: data
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
